name: CI Básico

on:
  push:
    branches:
      - master

jobs:
  Verificar-projeto:
    runs-on: ubuntu-latest

    steps:
      - name: baixar codigo
        uses: actions/checkout@v4

      - name: configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          
      - name: instalar dependências
        run: npm install    

      - name: verificar arquivos
        run:
          echo" Projeto recebido"
          ls -la

      - name: Finalizado
        run: echo "Pipeline executado com sucesso!"

